#!/bin/sh

echo "ПРОВОДНИК"
echo "✓ PPR [CODESPACES: SYMMETRIC... U"
echo "> screenshot"
echo "✓ src"
echo "> Pr"
echo "✓ Pr2"
echo "J CalculationResult.java U"
echo "J EnergyCalculator.java U"
echo "J SerializationDemo.java 1 , U"
echo "J Solver.java 1 , U"
echo "J Main.java 1 , M"
echo "✓ Test"
echo "J MainTest.java"
echo "J Test.java"
echo "$ pr.sh"
echo "→ README.md 1 U"